# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160513_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', upload_to='media/detail/Images'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', upload_to='media/genre/Images'),
        ),
    ]
