# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160513_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='audiosrc',
            field=models.FileField(blank='True', upload_to='media/shop/detail/Audio'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', upload_to='media/shop/detail/Images'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='videosrc',
            field=models.FileField(blank='True', upload_to='media/shop/detail/Video'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='audiosrc',
            field=models.FileField(blank='True', upload_to='media/shop/genre/Audios'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', upload_to='media/shop/genre/Images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='imgsrc',
            field=models.ImageField(blank='True', upload_to='media/shop/item/Pictures'),
        ),
    ]
