# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20160513_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='audiosrc',
            field=models.FileField(blank='True', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='videosrc',
            field=models.FileField(blank='True', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='genre',
            name='audiosrc',
            field=models.FileField(blank='True', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='genre',
            name='imgsrc',
            field=models.ImageField(blank='True', default='static/shop/images/nodisp.jpg', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='item',
            name='imgsrc',
            field=models.ImageField(blank='True', storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to=b''),
        ),
    ]
