# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160514_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='detailImgsrc',
            field=models.ImageField(blank='True', upload_to='media/shop/item/detail/Images'),
        ),
    ]
