# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_incart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=200)),
                ('orderPrice', models.IntegerField()),
                ('ordererMail', models.CharField(max_length=200)),
                ('ordererDir', models.CharField(max_length=200)),
            ],
        ),
    ]
