# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgsrc', models.ImageField(blank='True', upload_to='media/detail/Images')),
                ('audiosrc', models.FileField(blank='True', upload_to='media/detail/Audio')),
                ('videosrc', models.FileField(blank='True', upload_to='media/detail/Video')),
            ],
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='genre',
            name='audiosrc',
            field=models.FileField(blank='True', upload_to='media/genre/Audios'),
        ),
        migrations.AddField(
            model_name='genre',
            name='imgsrc',
            field=models.ImageField(blank='True', upload_to='media/genre/Images'),
        ),
        migrations.AddField(
            model_name='item',
            name='imgsrc',
            field=models.ImageField(blank='True', upload_to='media/item/Pictures'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
    ]
